//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TextAdventurez.Resource_Files {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TextAdventurez.Resource_Files.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dropped {0} in {1}.
        /// </summary>
        internal static string character_drop_successful {
            get {
                return ResourceManager.GetString("character_drop_successful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dropped {0} in {1}.
        /// </summary>
        internal static string character_drop_unsuccessful {
            get {
                return ResourceManager.GetString("character_drop_unsuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Picked up {0}.
        /// </summary>
        internal static string character_get_successful {
            get {
                return ResourceManager.GetString("character_get_successful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t pick up {0}.
        /// </summary>
        internal static string character_get_unsuccesful {
            get {
                return ResourceManager.GetString("character_get_unsuccesful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The door is locked.
        /// </summary>
        internal static string character_go_door_locked {
            get {
                return ResourceManager.GetString("character_go_door_locked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t go there.
        /// </summary>
        internal static string character_go_unsuccessful {
            get {
                return ResourceManager.GetString("character_go_unsuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You received a new item.
        /// </summary>
        internal static string character_use_successful {
            get {
                return ResourceManager.GetString("character_use_successful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find {0}.
        /// </summary>
        internal static string character_use_unsuccesful {
            get {
                return ResourceManager.GetString("character_use_unsuccesful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlocked {0}.
        /// </summary>
        internal static string exit_unlock_successful {
            get {
                return ResourceManager.GetString("exit_unlock_successful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong key.
        /// </summary>
        internal static string exit_unlock_unsuccessful {
            get {
                return ResourceManager.GetString("exit_unlock_unsuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find item \&quot;{0}\&quot;&quot;.
        /// </summary>
        internal static string game_use_unsuccessful {
            get {
                return ResourceManager.GetString("game_use_unsuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not recognize command.
        /// </summary>
        internal static string interpret_command_unsuccessful {
            get {
                return ResourceManager.GetString("interpret_command_unsuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not recognize direction.
        /// </summary>
        internal static string interpret_direction_unsuccessful {
            get {
                return ResourceManager.GetString("interpret_direction_unsuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0} cant be used on \&quot;{1}\&quot;&quot;.
        /// </summary>
        internal static string item_use_unsuccessful {
            get {
                return ResourceManager.GetString("item_use_unsuccessful", resourceCulture);
            }
        }
    }
}
