//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TextAdventurez.Resource_Files.Items {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Items {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Items() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TextAdventurez.Resource_Files.Items.Items", typeof(Items).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Banjo.
        /// </summary>
        internal static string banjo {
            get {
                return ResourceManager.GetString("banjo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bottle.
        /// </summary>
        internal static string bottle {
            get {
                return ResourceManager.GetString("bottle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opened bottle.
        /// </summary>
        internal static string bottle_opened {
            get {
                return ResourceManager.GetString("bottle_opened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cork Screw.
        /// </summary>
        internal static string cork_screw {
            get {
                return ResourceManager.GetString("cork_screw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mask.
        /// </summary>
        internal static string mask {
            get {
                return ResourceManager.GetString("mask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string none {
            get {
                return ResourceManager.GetString("none", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Silver key.
        /// </summary>
        internal static string silver_key {
            get {
                return ResourceManager.GetString("silver_key", resourceCulture);
            }
        }
    }
}
